# Generated by Django 4.2.1 on 2023-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('logo', models.ImageField(upload_to='supplier', verbose_name='logo')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('address', models.TextField(verbose_name='address')),
                ('fax', models.CharField(max_length=255, verbose_name='fax')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
            ],
        ),
    ]
