# Generated by Django 4.2.1 on 2023-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='id_supplier',
            field=models.CharField(default=1, max_length=255, verbose_name='supplier id'),
            preserve_default=False,
        ),
    ]
