# Generated by Django 4.2.1 on 2023-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_supplier_id_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(to='core.product', verbose_name='products'),
        ),
    ]
