# Generated by Django 4.2.1 on 2023-05-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_supplier_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='POrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='order date')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.CreateModel(
            name='POrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('price', models.IntegerField(verbose_name='price')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
                ('porder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.porder', verbose_name='purchare order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='porder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='supplier'),
        ),
    ]
