# Generated by Django 4.2.1 on 2023-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_porder_alter_supplier_account_porderdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porderdetail',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
