# Generated by Django 4.2.1 on 2023-05-27 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_porderdetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porderdetail',
            name='porder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.porder', verbose_name='purchare order'),
        ),
        migrations.AlterField(
            model_name='porderdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='porderdetail',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='quantity'),
        ),
    ]
