# Generated by Django 4.2.1 on 2023-05-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_supplier_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='porder',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
    ]
