# Generated by Django 4.2.1 on 2023-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_porder_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porder',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=255, null=True, verbose_name='status'),
        ),
    ]
