# Generated by Django 4.2 on 2023-05-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_porder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porder',
            name='status',
            field=models.CharField(blank=True, default='draft', max_length=255, null=True, verbose_name='status'),
        ),
    ]
