# Generated by Django 4.2 on 2023-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_porder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='porder',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
    ]
